services:
  s-ui:
    image: ghcr.io/admin8800/s-ui
    container_name: s-ui
    hostname: "s-ui"
    network_mode: host
    volumes:
      - "./db:/app/db"
      - "./cert:/usr/local/s-ui/cert"
      - "./acme:/root/.acme.sh"
    tty: true
    restart: unless-stopped
    entrypoint: "./entrypoint.sh"